//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratoryN20.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodService
    {
        public int ID { get; set; }
        public int BloodId { get; set; }
        public int ServiceCode { get; set; }
        public Nullable<long> Finished { get; set; }
        public bool Accepted { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int AnalyzerID { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> Result { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> LeadTimeInDays { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Blood Blood { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
