//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratoryN20.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterHistory
    {
        public int ID { get; set; }
        public System.DateTime Time { get; set; }
        public string UserLogin { get; set; }
        public bool IsSuccess { get; set; }
        public Nullable<int> IDUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
