//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratoryN20.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Blood = new HashSet<Blood>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public long DayOfBirth { get; set; }
        public string PassS { get; set; }
        public string PassN { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string SocialSecNumber { get; set; }
        public int InsuranceCompanyId { get; set; }
        public int SocialTypeID { get; set; }
        public string UA { get; set; }
        public string IpAddress { get; set; }
        public string Guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blood> Blood { get; set; }
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual SocialType SocialType { get; set; }
    }
}
